### ISSUE TITLE
Question：about `get_sent()` Function in get_inputs.py and the CXMI score

### ISSUE THREAD

**Issue by Linshou99** [zorazrw/filco#5]
I am encountering an issue while using the STRINC method to run `get_inputs.py` on the HotpotQA dev.json dataset to obtain inputs for the generative task. Specifically, I find that for all samples in the following code block (get_inputs.py line 130):

```python
elif inp == "filtered":
    sent = get_sent(
        example=example, 
        n_contexts=n_contexts, 
        criteria=filter_criteria,
        num_sents=num_sents,
        threshold=threshold, 
    )
```

the returned value `sent` from `get_sent()` is consistently an empty string (`""`). Consequently, in the subsequent steps, all samples enter the get_context() function to obtain the first context passage as supplementary context. Upon reviewing the relevant code snippet in `get_sent()` (get_inputs.py line 57):

```python
if criteria == "strinc":
    for sent_dict in example["ctxs"][idx]["sentences"]:
        if sent_dict[criteria] is True:
            sentences.append(sent_dict["text"])
```

I am considering whether the condition `sent_dict[criteria] is True` should be replaced with `sent_dict[criteria] == True`, since the type of strinc scores is float based on the return type of the `has_answer()` function. And `True` and `float(1.0)` are distinct objects. When I made the modification, `get_sent()` did indeed yield non-empty string returns.

Moreover, Is the generation model used in calculating the CXMI score an unfine-tuned flan-t5-xl model?
I run this model on HotpotQA dev.json and find that all sentences have a CXMI score greater than 0.0, which means that every sentence is a valid context. I wonder if this is normal. I would appreciate any insights  you can provide.

Thank you for your assistance.

**Comment by zorazrw** [comment]
Hi! thanks for pointing this out. This is caused by a change in our processing scripts (particularly `eval/has_answer` function) from returning a boolean value to a float (0.0 or 1.0) value. I've updated the script to `if sent_dict[criteria]:`, which should equivalently solve your problem as `sent_dict[criteria] == True`.

Regarding your question about CXMI: yes, we use an unfine-tuned flan-t5-xl in our experiments. The CXMI scores may happen to be mostly positive values. In this scenario, you can consider increasing the value of the `threshold` argument for the `get_inputs.py` file, e.g., to 0.2, to make the filtering effective.
